USE [master]
GO
/****** Object:  Database [ScreenSaver]    Script Date: 12/24/2021 1:38:33 PM ******/
CREATE DATABASE [ScreenSaver]

GO
ALTER DATABASE [ScreenSaver] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ScreenSaver] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ScreenSaver] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ScreenSaver] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ScreenSaver] SET ARITHABORT OFF 
GO
ALTER DATABASE [ScreenSaver] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ScreenSaver] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ScreenSaver] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ScreenSaver] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ScreenSaver] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ScreenSaver] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ScreenSaver] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ScreenSaver] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ScreenSaver] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ScreenSaver] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ScreenSaver] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ScreenSaver] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ScreenSaver] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ScreenSaver] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ScreenSaver] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ScreenSaver] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ScreenSaver] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ScreenSaver] SET RECOVERY FULL 
GO
ALTER DATABASE [ScreenSaver] SET  MULTI_USER 
GO
ALTER DATABASE [ScreenSaver] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ScreenSaver] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ScreenSaver] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ScreenSaver] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ScreenSaver] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ScreenSaver] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'ScreenSaver', N'ON'
GO
ALTER DATABASE [ScreenSaver] SET QUERY_STORE = OFF
GO
USE [ScreenSaver]
GO
/****** Object:  Table [dbo].[GenerateCodes]    Script Date: 12/24/2021 1:38:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GenerateCodes](
	[CodeID] [int] IDENTITY(1,1) NOT NULL,
	[GroupID] [int] NOT NULL,
	[Code] [nvarchar](256) NOT NULL,
	[ExpirationDate] [datetime] NOT NULL,
	[UserID] [int] NOT NULL,
 CONSTRAINT [PK_GenerateCodes] PRIMARY KEY CLUSTERED 
(
	[CodeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Groups]    Script Date: 12/24/2021 1:38:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Groups](
	[GroupID] [int] IDENTITY(1,1) NOT NULL,
	[GroupName] [nvarchar](50) NOT NULL,
	[OwnerID] [int] NOT NULL,
 CONSTRAINT [PK_Groups] PRIMARY KEY CLUSTERED 
(
	[GroupID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[GroupUsers]    Script Date: 12/24/2021 1:38:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GroupUsers](
	[UserID] [int] NOT NULL,
	[GroupID] [int] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Images]    Script Date: 12/24/2021 1:38:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Images](
	[ImageID] [int] IDENTITY(1,1) NOT NULL,
	[GroupID] [int] NOT NULL,
	[ImageName] [nvarchar](150) NOT NULL,
	[Image] [image] NOT NULL,
	[Date] [datetime] NOT NULL,
 CONSTRAINT [PK_Images] PRIMARY KEY CLUSTERED 
(
	[ImageID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 12/24/2021 1:38:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[UserID] [int] IDENTITY(1,1) NOT NULL,
	[Username] [nvarchar](50) NOT NULL,
	[Password] [nvarchar](max) NOT NULL,
	[Email] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[GenerateCodes]  WITH CHECK ADD  CONSTRAINT [FK_GenerateCodes_Groups] FOREIGN KEY([GroupID])
REFERENCES [dbo].[Groups] ([GroupID])
GO
ALTER TABLE [dbo].[GenerateCodes] CHECK CONSTRAINT [FK_GenerateCodes_Groups]
GO
ALTER TABLE [dbo].[GenerateCodes]  WITH CHECK ADD  CONSTRAINT [FK_GenerateCodes_Users] FOREIGN KEY([UserID])
REFERENCES [dbo].[Users] ([UserID])
GO
ALTER TABLE [dbo].[GenerateCodes] CHECK CONSTRAINT [FK_GenerateCodes_Users]
GO
ALTER TABLE [dbo].[Groups]  WITH CHECK ADD  CONSTRAINT [FK_Groups_Users] FOREIGN KEY([OwnerID])
REFERENCES [dbo].[Users] ([UserID])
GO
ALTER TABLE [dbo].[Groups] CHECK CONSTRAINT [FK_Groups_Users]
GO
ALTER TABLE [dbo].[GroupUsers]  WITH CHECK ADD  CONSTRAINT [FK_GroupUsers_Groups] FOREIGN KEY([GroupID])
REFERENCES [dbo].[Groups] ([GroupID])
GO
ALTER TABLE [dbo].[GroupUsers] CHECK CONSTRAINT [FK_GroupUsers_Groups]
GO
ALTER TABLE [dbo].[GroupUsers]  WITH CHECK ADD  CONSTRAINT [FK_GroupUsers_Users] FOREIGN KEY([UserID])
REFERENCES [dbo].[Users] ([UserID])
GO
ALTER TABLE [dbo].[GroupUsers] CHECK CONSTRAINT [FK_GroupUsers_Users]
GO
USE [master]
GO
ALTER DATABASE [ScreenSaver] SET  READ_WRITE 
GO
